#!/bin/bash

repo=${PWD##*/}
description=''
SSH='false'
remote_name='origin'
initialize=''

while getopts 'd:n:r:si:' flag; do
  case "${flag}" in
	d) description="${OPTARG}";;
	n) repo="${OPTARG}";;
	r) remote_name="${OPTARG}";;
	s) SSH='true';;
	i) initialize="${OPTARG}";;
    *) error "Unexpected option -${flag}";;
  esac
done

if [ -z $(which git) ]; then
	printf "The program 'git' is currently not installed.\n"
	exit 1
elif [ $(git remote) == $remote_name ]; then
	printf "fatal: remote $remote_name already exists.\n"
fi

if [ -z $(which expect) ]; then
	printf "The program 'expect' is currently not installed.\n"
	exit 1
fi

if [ "$initialize" ]; then
	git init
	git add *
	git commit -m "$initialize"
fi

read -r -p "Enter host username: " username

read -rs -p "Enter password for user '$username': " password
curl -u "$username:$password" https://api.github.com/user/repos -d '{"name":"'$repo'", "private":"true", "description":"'$description'"}'

git remote add $remote_name https://github.com/$username/$repo.git

if $SSH ; then
	git remote set-url $remote_name git@github.com:$username/$repo.git
	git push $remote_name master
else
	expect -f creds.expect $username $password $remote_name
fi